title: Andres Perez Martinez
description: <h1>Andres</h1> I'm a data scientist/analyst with practical project experience. I completed my bachelor's degree in Economics at Sacramento State and recently obtained a Master of Science in Quantitative Economics from Cal Poly SLO. I am genuinely passionate about using data-driven insights to take on complex challenges and make meaningful decisions. I'm excited to apply my analytical skills and creativity to contribute to the field of data science.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
